### ISSUE TITLE
Tags are weird

### ISSUE THREAD

**Issue by Kolkies** [YorkAARGH/York-Dev#20]
When i do:
https://i.kolkiesdev.nl/5b0c74b3-0308-427e-86a4-224358dee93d.png
I get an weird answer.
I think that that isn't the way it should go.

Is this fixable?

**Comment by YorkAARGH** [comment]
The way the tags are design, you're able to tag users with them, but I will look into it.

**Comment by YorkAARGH** [comment]
[This line](https://github.com/YorkAARGH/York-Dev/blob/master/events/message.js#L44-L46) is what's causing the "issue", as you can see it combines the arguments you supply and apply them before the tag is sent.
