### ISSUE TITLE
Use badges!

### ISSUE THREAD

**Issue by jacc** [YorkAARGH/York-Dev#46]
https://support.codacy.com/hc/en-us/articles/212799365-Badges This will make the repo visually more pleasing and draw attention so the first thing people see is the grade.

**Comment by YorkAARGH** [comment]
There should be one on the readme
![](http://evie.ban-hammered.me/i/1310n.png)

**Comment by jacc** [comment]
![screen shot 2017-11-22 at 2 48 12 pm](https://user-images.githubusercontent.com/6956351/33146982-2f683cd4-cf94-11e7-8573-116fa095ffa8.png) I meant something like this.

**Comment by YorkAARGH** [comment]
I'm aware of what you speak of, but that image is showing you a textual fall back for the badge, it should be an image but some reason it's not showing as an image.

**Comment by YorkAARGH** [comment]
Okay, turns out the hash changed for the project, it's fixed now.

**Comment by jacc** [comment]
👍🏻
