### ISSUE TITLE
Add a default emoji to new guilds

### ISSUE THREAD

**Issue by TaiweiLoh** [YorkAARGH/York-Dev#9]
![image](https://user-images.githubusercontent.com/30280397/31261580-988ae5f2-aab1-11e7-865d-ce624ea4b917.png)
As you can see: undefined. Add a default emoji for new guild joined. I added the bot via the dashboard

**Comment by YorkAARGH** [comment]
By default, until you enable custom emoji, should be a unicode $, as seen here in the [example config](https://github.com/YorkAARGH/York-Dev/blob/master/config.js.example#L40-L42)

**Comment by TaiweiLoh** [comment]
Wierd. It didn't apply default, another person has said as well.

**Comment by YorkAARGH** [comment]
Can't reproduce sorry.
